FROM node

USER root
RUN mkdir -p /opt/app/dist

RUN npm install -g nodemon

COPY package.json /tmp/package.json
RUN cd /tmp && npm install

RUN cp -a /tmp/node_modules/ /opt/app/node_modules/ && \
    cd /opt/app

ADD . /opt/app/
WORKDIR /opt/app

CMD ["npm", "run", "dev"]